config/routes.rb
Rails.application.routes.draw do
  root to: "plans#top"
  
  # post 'comments/create', to: 'comment#create', as: :comment_create
  resources :comments
  
   devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  
  resources :favorites 
  
  resources :plans do
    
    collection do
      post :confirm
    end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :comments ,dependent: :destroy 
  mount_uploader :image, ImageUploader
  validates :lessondate, presence: true
  validates :goal, presence: true, length:{in:1..100}
  validates :item, presence: true
  validates :content, presence: true
  belongs_to :user
  
  def self.search(search) # self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      # Plan.where(['name LIKE ?', "%#{search}%"])
      Plan.where(['item LIKE ?', "%#{search}%"])
    else
      Plan.all #全て表示。
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index,:new, :show, :edit, :update, :destroy]
  
  def top
  end
  
  def index
    @plans = current_user.plans.all
    # binding.pry
    @plans = @plans.search(params[:search])
   
  end
  
  def new
    # @plan = current_user.plan.news.build
    if params[:back]  
      @plan = Plan.new
      @plan.image.retrieve_from_cache! params[:cache][:image]
    else 
      @plan = Plan.new
    end
  end
  
  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id
      if @plan.save
      redirect_to plans_path, notice: "教案作成しました！"
    
      else
      render 'new'  
      end
    
  end
  
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.pdf do
        # 詳細画面のHTMLを取得
        html = render_to_string template: "plans/show"

        # PDFKitを作成
        pdf = PDFKit.new(html, encoding: "UTF-8")

        pdf.stylesheets << "#{Rails.root}/app/assets/stylesheets/plans.scss"
        pdf.stylesheets << "#{Rails.root}/app/assets/stylesheets/bootstrap.min.css"
        
        # 画面にPDFを表示する
        # to_pdfメソッドでPDFファイルに変換する
        # 他には、to_fileメソッドでPDFファイルを作成できる
        # disposition: "inline" によりPDFはダウンロードではなく画面に表示される
        send_data pdf.to_pdf,
          filename:    "#{@plan.id}.pdf",
          type:        "application/pdf",
          disposition: "inline"
      end
    end

    @plan = Plan.find(params[:id])
    @newcomment = Comment.new(:plan_id => params[:id])
    @comments = Comment.where(plan_id: params[:id])
    
    
    # @plan = Plan.find(params[:id])
    
    @favorite = current_user.favorites.find_by(plan_id: @plan.id)  
  end
  
  def comment
  end
  
  def edit
  end
  
  def update
    if @plan.update(plan_params)
       redirect_to plans_path, notice:"更新しました。"
    else
     render 'new'
    end
  end
  
  def destroy
    @plan.destroy
    redirect_to plans_path, notice:"削除しました。"   
    
    # favorite = current_user.favorites.find_by(id: params[:id]).destroy
    # redirect_to plans_url, notice: "教案をポートフォリオから解除しました"
  end
  
  def confirm
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id
    render :new  if @plan.invalid?  
  end
  
  def comment
    # @plan.user_id = current_user.id
    @plan = Plan.find(params[:id])
  end
  
  private
  def plan_params
    # params[:plan]
    params.require(:plan).permit(:lessondate, :goal, :item, :content, :image,:image_cache)
  end
  
  def set_plan
    # @plan = current_user.plans.find(params[:id])
    @plan = Plan.find(params[:id])
  end

  # def correct_user
  #   @user = User.find(params[:id])
  #   redirect_to(root_path) unless current_user?(@user)
  # end
  
end

app/helpers/plans_helper.rb
module PlansHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_plans_path
    elsif action_name == 'edit'
      plan_path
    end
  end  
end

app/views/plans/_form.html.erb
<%= form_with(model: @plan, local: true, url: choose_new_or_edit) do |form| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h4><%= @plan.errors.count %>件のエラーがあります。</h4>
      <ul>

      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br>  
  <div class = "container">
    <table class="table">
    <tr>
      <th>LessonDate</th>
      <td><%= form.date_field :lessondate, :start_date => Time.now.year.month.day %></td>
    </tr>
    <tr>
      <th>Item</th>
      <td><%= form.text_field :item, :size=>"50x3" %></td>
    </tr>
    <tr>
      <th>Goal</th>
      <td><%= form.text_area :goal, :size=>"70x3" %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td><%= form.text_area :content, :size=>"80x20" %></td>
    </tr>
    <tr>
      <th>Image</th>
      <td><%= image_tag(@plan.image.url) if @plan.image.url %>
          <%= form.file_field :image, id: :plan_image, :size=>"15x15" %></td>
    </tr>
  </table>
  <div class = "linkbtn">
   <%= form.submit 'CREATE', class: 'btn btn-primary btn-lg' %>
  </div>
 </div>
  <% end %>
  <br>
  
<div class ="linkbtn">
 <%= link_to "Back to teaching plans", plans_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/plans/comment.html.erb
<br>
<h1 class="lists_title container-fluid titles">Teaching Plan</h1>
   
   <h3>after comment</h3>
   <h1><%= @plan.title %></h1>
   <% @comments.each_with_index do |comment , idx| %>
    <p>
      <%= idx + 1 %>. <%= comment.name %> : <%= comment.body %>
    </p>
   <% end %>

   <h3>新規書き込み</h3>
   <%= form_for @newcomment, :url => comment_create_path do |f| %>
     <p>コメント</p>
     <p><%= f.text_area :body %></p>
    <%= f.hidden_field :plan_id %>
    <%= f.submit %>
   <% end %>

   <div class = "container">
    <table class="table">
    <tr>
      <th>LessonDate</th>
      <td><%= @plan.lessondate %></td>
    </tr>
    <tr>
      <th>Item</th>
      <td><%= simple_format(@plan.item) %></td>
    </tr>
    <tr>
      <th>Goal</th>
      <td><%= simple_format(@plan.goal) %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td class = "contentfield"><%= simple_format(@plan.content) %></td>
    </tr>
    <tr>
      <th>Image</th>
      <td><%= image_tag @plan.image %></td>
    </tr>
  </table>
 
#  <!--<h3 class="titles">After Commnents</h3>-->
  <!--  <%#= form_with([@plan, @plan.comments.build]) do |form| %>-->
  <!--<p>-->
  <!--  <%#= form.text_field :body %>-->
  <!--</p>-->
  <!--<p>-->
  <!--  <%#= form.submit %>-->
  <!--</p>-->
  <!--<%# end %>-->

<br>
<div class ="linkbtn">
 <%= link_to "Back to plan Lists", plans_path, class: "btn btn-primary btn-lg btn-block" %>
</div>

app/views/plans/confirm.html.erb
<h3 class="titles">CONFIRM new Teaching Plan</h3>
<br>
<%= form_with(model: @plan, url: plans_path, local: true) do |form| %>
  <%= form.hidden_field :lessondate %>
  <%= form.hidden_field :goal %>
  <%= form.hidden_field :item %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  
<div class = "container">
    <table class="table">
    <tr>
      <th>LessonDate</th>
      <td><%= @plan.lessondate %></td>
    </tr>
    <tr>
      <th>Item</th>
      <td><%= simple_format(@plan.item) %></td>
    </tr>
    <tr>
      <th>Goal</th>
      <td><%=  simple_format(@plan.goal) %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td class = "contentfield"><%= simple_format(@plan.content) %></td>
    </tr>
    </table>
    <div>
      <p>Image</p>
      <%= image_tag(@plan.image) %>
    </div>
<br>
   <div class ="linkbtn">
    <%= form.submit 'SAVE', class: 'btn btn-primary btn-lg btn-block' %>
   </div>
<% end %>

<%= form_with(model: @plan, url: new_plan_path, local: true, method: 'post') do |form| %>
  <%= form.hidden_field :lessondate %>
  <%= form.hidden_field :goal %>
  <%= form.hidden_field :item %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
 
 <br>
 <div class ="linkbtn">
   <%= form.submit 'back', class: 'btn btn-danger btn-lg btn-block' %>
 </div>
</div>
<% end %>
 

app/views/plans/edit.html.erb
<div class = "newplan">
    
  <h2 class ="titles">EDIT your Teaching Plan</h2>

  <%= render 'form' %>
  
</div>

app/views/plans/index.html.erb
<h1 class="lists_title container-fluid titles">Teaching Plan Lists</h1>

<%= form_tag plans_path, :method => 'get' do %>
  <p class = "searchbox">
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Item Search",:name => nil %>
  </p>
<% end %>

<p class = "notice"></p>

<%# if user_id == current_user.id %>
<%# binding.pry %>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>LessonDate</th>
        <th>Item</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @plans.each do |plan| %>
        <tr>
          <td><%= plan.lessondate %></td>
          <td><%= plan.item %></td>
          <td><%= link_to 'Show', plan, class: 'btn btn-success btn-lg' %></td>
          <td><%= link_to 'Edit', edit_plan_path(plan), class: 'btn btn-info btn-lg' %></td>
          <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-lg' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%# end %>

<div class = "linkbtn">
<%= link_to 'CREATE new Teaching Plan', new_plan_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/plans/new.html.erb
<div class = "newplan">
<br>
  <h2 class = "titles">CREATE Teaching Plan</h2>

  <%= render 'form' %>
</div>

app/views/plans/show.html.erb
<link href="https://fonts.googleapis.com/earlyaccess/kokoro.css" rel="stylesheet" />

<br>
<h1 class="lists_title container-fluid titles">Teaching Plan</h1>

   <div class = "container">
    <table class="table">
    <tr>
      <th>LessonDate</th>
      <td><%= @plan.lessondate %></td>
    </tr>
    <tr>
      <th>Item</th>
      <td><%= simple_format(@plan.item) %></td>
    </tr>
    <tr>
      <th>Goal</th>
      <td><%= simple_format(@plan.goal) %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td class = "contentfield"><%= simple_format(@plan.content) %></td>
    </tr>
  </table>
    <div>
      <p>Image</p>
      <%= image_tag @plan.image %>
    </div>
 
<div class ="linkbtn">
<%= link_to "PDF",
              plan_path(@plan, format: "pdf"),
              :class => 'btn btn-warning btn-lg' %>
</div>
<br>

   <h3 class="titles">after comment</h3>
   <% @comments.each_with_index do |comment , idx| %>
    <p class="aftercomment">
      <%= idx + 1 %>. : <%= comment.body %>
    </p>
   <% end %>

   <!--<h5>new comment</h5>-->
   <%= form_for @newcomment, :url => comments_path do |f| %>
     <p class="titles">new comment</p>
     <p class="commentarea"><%= f.text_area :body, :size=>"70x3" %></p>
    <%= f.hidden_field :plan_id %>
    <div class="commentarea"><%= f.submit 'post' %></div>
   <% end %>

<br>
<%# unless @plan.user_id == current_user.id %>
<div class ="linkbtn">
  <% if @favorite.present? %>
    <%= link_to 'DELETE Portfolio', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'ADD Portfolio', favorites_path(plan_id: @plan.id), method: :post, class: 'btn btn-basic' %>
  <% end %>
<%# end %>
</div>
<br>
<div class ="linkbtn">
<%= link_to "Back to plan Lists", plans_path, class: "btn btn-primary btn-lg btn-block" %>
</div>
<br>

app/views/plans/show.pdf.erb
<!--# app/views/plans/show.pdf.erb-->
<%- model_class = Plan -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Lesson Date:</strong></dt>
  <dd><%= @plan.lessondate %></dd>
  
  <dt><strong>Item:</strong></dt>
  <dd><%= simple_format(@plan.item) %></dd>
  
  <dt><strong>Goal:</strong></dt>
  <dd><%= simple_format(@plan.goal) %></dd>
  
  <dt><strong>Content:</strong></dt>
  <dd><%= simple_format(@plan.content) %></dd>
  
</dl>

app/views/plans/top.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Stylish Portfolio - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/stylish-portfolio.min.css" rel="stylesheet">

  </head>

    <!-- Header -->
    <header class="masthead d-flex">
      <div class="container text-center my-auto">
        <h1 class="mb-1">Teaching Port</h1>
        <h3 class="mb-5">
          <em>A space stock your TeachingPlan & sharing Portforio</em>
        </h3>
      <div class="overlay"></div>
    </header>

    <!-- Services -->
    <section class="content-section bg-primary text-white text-center" id="services">
      <div class="container">
        <div class="content-section-heading">
          <h3 class="text-secondary mb-0">Services</h3>
          <h2 class="mb-5">What We Offer</h2>
        </div>
        <div class="row">
          <div class="col-lg-6 col-md-6 mb-5 mb-lg-0">
            <!--条件分岐 ログインしてたら、plans/newへ してなかったら、user/sign_inへ-->
            <% if user_signed_in? %>  
              <a class="service-icon rounded-circle mx-auto mb-3" href="/plans/">
                <i class="icon-pencil"></i>
              </a>
            <% else %>
              <a class="service-icon rounded-circle mx-auto mb-3" href="users/sign_in">
                <i class="icon-pencil"></i>
              </a>  
            <% end%>
              <h4>
                <strong>TeachingPlan</strong>
              </h4>
            <p class="text-faded mb-0">You can create your Teaching Plan.</p>
          </div>
          <div class="col-lg-6 col-md-6 mb-5 mb-md-0">
            <span class="service-icon rounded-circle mx-auto mb-3">
              <i class="icon-like"></i>
            </span>
            <h4>
              <strong>Portfolio</strong>
            </h4>
            <p class="text-faded mb-0">You can shere your TeachingPlan as your portfolio!</p>　
            <p>*UNDER CONSTRUCTION!!*</p>
          </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="footer text-center">
      <div class="container">
        <ul class="list-inline mb-5">
          <li class="list-inline-item">
            <a class="social-link rounded-circle text-white mr-3" href="#" >
              <i class="icon-social-facebook"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a class="social-link rounded-circle text-white mr-3" href="#">
              <i class="icon-social-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a class="social-link rounded-circle text-white" href="#">
              <i class="icon-social-github"></i>
            </a>
          </li>
        </ul>
       </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="js/stylish-portfolio.min.js"></script>

  </body>

</html>