config/routes.rb
Rails.application.routes.draw do
  root to: "plans#top"
  
  # post 'comments/create', to: 'comment#create', as: :comment_create
  resources :comments
  
   devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  
  resources :favorites 
  
  resources :plans do
    
    collection do
      post :confirm
    end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teachingport</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="bootstrap.min.css">
    <link rel="stylesheet" href="cb-materialbtn.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bad+Script" rel="stylesheet">
  </head>

  <body>
     <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <a class="navbar-brand" href="/">Teaching Port</a>
    </nav>
    <nav class="thinline">
    </nav>
    
    <div class="container-fluid">
    <% if user_signed_in? %>
      <%= link_to "CREATE ", new_plan_path, class: 'btn btn-cyan300_flt btn-lg btnsizea' %>
      <%= link_to "LOG OUT ", destroy_user_session_path, method: :delete, class: 'btn btn-amber100_ftg btn-lg btnsizeb'%>
      <%= link_to "PLAN LISTS ", plans_path, class: 'btn btn-blue50_rsd btn-lg btnsizec'%>
      <%= link_to 'Portfolio', favorites_path, class: 'btn btn-lime100_rsd btnsizea' %>
      <%= link_to "TOP", root_path, class: 'btn btn-biuegray200_flt btn-lg btnsizeb' %>
    <% else %>
      <%= link_to "SIGN UP", new_user_registration_path, class: 'btn btn-lightgreen100_ftg btn-lg btnsizec' %>
      <%= link_to "LOG IN", new_user_session_path, class: 'btn btn-amber200_ftg btn-lg btnsizeb' %>
      <%= link_to "TOP", root_path, class: 'btn btn-biuegray200_flt btn-lg btnsizeb' %>
    <% end %>
    </div>
   <br>
   <div class="noticearea">
    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
   </div>
   
    <%= yield %>
    
   <nav class="thinline">
   </nav>
  
   <footer class="sticky-footer bg-dark fixed-bottom">
      <div class="container">
        <div class="text-center ft">
          <small>Copyright © MinahoWatabe 201802</small>
        </div>
      </div>
   </footer>
  
  </body>
</html>

app/views/layouts/pdf.html.erb
<html>
  <head>
    <meta charset="utf-8" ?>
    <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
  <head>
  <body>
    <div class="header">header</div>
    <%= yield %>
    <div class="footer">footer</div>
  </body>
<%= yield %>
</html>

<!--<html>-->
<!--  <head>-->
<!--    <meta http-equiv="content-type" content="text/html; charset=utf-8" />-->
<!--    <%#= wicked_pdf_stylesheet_link_tag    'application', 'data-turbolinks-track': 'reload' %>-->
<!--    <%#= wicked_pdf_javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>-->
<!--  <head>-->
<!--  <body>-->
<!--    <div class="header">header</div>-->
<!--    <%#= yield %>-->
<!--    <div class="footer">footer</div>-->
<!--  </body>-->
<!--<%#= yield %>-->
<!--</html>-->